### ISSUE TITLE
what should an equation return?

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/equipment-register-schema#14]
Currently, the documentation for the _value_ from the `<equation>` states that it returns the _corrected_ value.

Should it return the _correction_ to apply to the value? e.g., $\Delta{t}$ in $t=T +\Delta{t}$ (like what is expressed in reports from the Humidity team).

Similarly, this needs to be decided for the _uncertainty_ `<equation>`.

**Comment by rebeccahawke** [comment]
I would prefer the corrected value, as it stands, to make sure that the correction is applied correctly! 

The uncertainty would be the actual uncertainty value? Or are you referring to the standard/expanded debate?

**Comment by jborbely** [comment]
I prefer the corrected value as well.

> Or are you referring to the standard/expanded debate?

Yes, just thinking about that debate

**Comment by jborbely** [comment]
Decision: Returns the _corrected_ value.
