### ISSUE TITLE
Add more allowed laboratory locations

### ISSUE THREAD

**Issue by rebeccahawke** [MSLNZ/equipment-register-schema#15]
https://github.com/MSLNZ/equipment-register-schema/blob/daffbfa0611fe9d6eb850ab1e42ed063495ef134/equipment-register.xsd#L79

Could we please add 'Mass Standards laboratories', 'Pressure Standards laboratories', 'Kibble Balance', and 'Long room' to this enum (and/or the RMG room numbers?)

**Comment by jborbely** [comment]
Fixed in e1b2ed1ae6350fcb1a4177b2af0666189eff0d51
