### ISSUE TITLE
Additional enumeration values

### ISSUE THREAD

**Issue by rebeccahawke** [MSLNZ/equipment-register-schema#20]
Please may we have the following keywords added to the respective enumerations?

"Balance" to equipment keywordsList:
_line 34:                   <xsd:enumeration value="Balance"/>_ 
"Mass" to measurand quantityEnumerationString:
_line 202:            <xsd:enumeration value="Mass"/>_

Thank you :)

**Comment by jborbely** [comment]
Fixed in 29ed822b31a94abf4a98ee1563a267e55729c9ba
