### ISSUE TITLE
use proper XML syntax for a table of calibration-report data

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/equipment-register-schema#6]
The `data` subelement in the `table` element currently uses a _CSV string_ to represent the calibration report, e.g.

```xml
<data>
  250, 0.018184693, 0.020338474
  300, 0.184783924, 0.017558388
</data>
```

Should the table be more XML like, e.g.,
```xml
<data>
  <row>
    <col>250</col>
    <col>0.018184693</col>
    <col>0.020338474</col>
  </row>
  <row>
    <col>300</col>
    <col>0.184783924</col>
    <col>0.017558388</col>
  </row>
</data>
```

**Comment by rebeccahawke** [comment]
I much prefer the more readable tabular format. As discussed, we just need to find a format that is reliably interpretable by both numpy and other programs (C#, Delphi, ...) e.g. when we have comments in the table, or floats where the decimal separator is a comma.

**Comment by jborbely** [comment]
I agree, tabular is more readable. It is trivial for a programming language to split each row on the `\n` character then split each column on the _delimiter_ character(s) and it is easy (quick) for someone to audit when you can align columns. This is a one-line call to [numpy.loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) for Python users.

To bypass the _delimiter_ issue, we could either

1. force the `<header>`, `<datatype>` and `<data>` elements to have a `delimiter` attribute (to allow for different delimiters?? sounds excessive) 
2. add a `<delimiter>` element and some (all?) other elements must adhere to the specified delimiter character(s). 
3. state that a `,` is the only allowed delimiter character and people who want to use `,` as a decimal separator cannot.

**Comment by jborbely** [comment]
Decide to keep using the CSV format with  `,` as the only allowed delimiter.

If, for some reason, a `<delimiter>` element becomes necessary, it can be added later, and, to maintain backwards compatibility, if the `<delimiter>` element is missing the default value will be `,`
