### ISSUE TITLE
handling both software/firmware versions of equipment

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/equipment-register-schema#7]
Currently an `equipment` element requires a `firmware` element, but _ISO:17025 Clause 6.4.13 a)_ specifies both software and firmware versions should be specified.

We should figure out how to specify both and to make sure that the software/firmware elements are implemented appropriately because the software/firmware values may be related.

**Comment by jborbely** [comment]
The following are informal definitions what  `software` and `firmware` could refer to.

**Software**: Provided by the manufacturer of the equipment and may be installed/updated by an end user on any computer. The manufacturer of the equipment may provide this _software_ as, for example, a graphical user interface (GUI) and/or as a software development kit (SDK) to interface with the equipment. _Software_ should not represent the version of the custom code that is written by someone at MSL to interact with the equipment. While the code version is important, it should not be part of the equipment register, but, should be handled in a different manner, e.g., as metadata in a file when acquiring data.

**Firmware**: Embedded within the equipment. May be updated by either the manufacturer and/or the end user.

The primary difference is that the **Firmware** version has a single value of truth -- it is independent of where the equipment is physically located and independent of which computer is used to interface with it; whereas, the **Software** version depends on which computer (perhaps even on which executable is run on the same computer) is used to interface with the equipment and therefore there may not be a single value of truth that can be defined in the equipment register.

**Comment by rebeccahawke** [comment]
I would be inclined to avoid including software information in the equipment register for the reasons you've provided, and instead note that it is a requirement for the user to record the software version when collecting data from the equipment "where applicable".  If desired, this information could be included as part of a separate connections register, as the software is likely to depend on the specific computer used to interface with the equipment.

**Comment by jborbely** [comment]
Fixed in bf2a255353770ab96c073ab9be029771d289db77. Document the difference between _software_ and _firmware_.

Only `<firmware>` version(s) shall be specified in an equipment register. Software version(s) should be specified in the file that is generated during data acquisition.
