### ISSUE TITLE
include the hash value of a calibration-report file

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/equipment-register-schema#8]
If the data of a calibration report is stored in an external file (i.e., not stored within the equipment-register file itself), the `file` element should contain a, for example, `sha256` subelement that represents the hash value of the calibration-report file.

**Comment by rebeccahawke** [comment]
Yes this is a good idea.  Perhaps it might be worth clarifying that this hash value is equivalent to the checksum and/or provide a link to some guidance on how to generate the hash value if not the standard checksum used by MSL already?

**Comment by jborbely** [comment]
Good idea about adding guidance on how to calculate it.

If you build and view the docs, the popup help window for the `<sha256>` element is as follows

![image](https://github.com/MSLNZ/equipment-register-schema/assets/4319367/4f6b5945-46cc-4d6f-9cf8-a15c3a749aa8)
