### ISSUE TITLE
should the uncertainty element be a string, a float or a complexType?

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/equipment-register-schema#9]
Currently, when using an `equation` to store the calibration information, the `uncertainty` element is of type `xsd:float`. Should `uncertainty` be of type `xsd:string` that represents another equation to parse or a `xsd:complexType` that could potentially represent another situation?

**Comment by rebeccahawke** [comment]
As discussed, the value and the uncertainty could both be expressed as either a float or an equation depending on the situation. One solution is to allow these elements to each be an equation (xsd:string), with a 'variables' attribute that stores the equation variable(s) if applicable.
